inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/TrailingWhitespace:
  Enabled: true
