services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
      - rubygems:/usr/local/bundle
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c 'bin/setup && rails server -b 0.0.0.0 -p 3000'
volumes:
  rubygems:
  postgres:
